"""
Report Generator Agent - Powered by Gemini
Synthesizes all findings into human-readable outputs.
"""

import os
import json
from typing import Dict, Any
import nbformat as nbf

try:
    from google import genai
    GENAI_AVAILABLE = True
except ImportError:
    GENAI_AVAILABLE = False


class ReportGeneratorAgent:
    """
    Agent responsible for generating reports and notebooks.
    
    Uses Gemini to:
    - Synthesize findings from all agents
    - Generate human-readable insights
    - Create Jupyter notebooks
    - Write executive summaries
    """
    
    def __init__(self, api_key: str = None):
        self.name = "ReportGenerator"
        
        if GENAI_AVAILABLE and api_key is None:
            api_key = os.getenv('GOOGLE_API_KEY')
        
        if GENAI_AVAILABLE and api_key and api_key != 'your_gemini_api_key_here':
            try:
                self.client = genai.Client(api_key=api_key)
                self.model = os.getenv('GEMINI_MODEL', 'gemini-2.0-flash-exp')
                self.gemini_enabled = True
                print(f"✓ {self.name} Agent initialized with Gemini")
            except:
                self.gemini_enabled = False
                print(f"✓ {self.name} Agent initialized (fallback mode)")
        else:
            self.gemini_enabled = False
            print(f"✓ {self.name} Agent initialized (fallback mode)")
    
    def generate_reports(self, strategy: Dict, eda_results: Dict, 
                        features: Dict, models: Dict,
                        output_dir: str, notebooks_dir: str) -> Dict[str, str]:
        """
        Generates all reports and notebooks.
        
        Args:
            strategy: Competition strategy from CompetitionReader
            eda_results: EDA results from DataExplorer
            features: Feature engineering results
            models: Model training results
            output_dir: Directory for reports
            notebooks_dir: Directory for notebooks
            
        Returns:
            Dictionary with paths to generated files
        """
        generated_files = {}
        
        # 1. Executive Summary
        summary_path = f"{output_dir}/executive_summary.md"
        summary = self._generate_executive_summary(strategy, eda_results, features, models)
        with open(summary_path, 'w') as f:
            f.write(summary)
        generated_files['executive_summary'] = summary_path
        
        # 2. Model Comparison Report
        model_report_path = f"{output_dir}/model_comparison.md"
        model_report = self._generate_model_report(models)
        with open(model_report_path, 'w') as f:
            f.write(model_report)
        generated_files['model_comparison'] = model_report_path
        
        # 3. EDA Notebook
        eda_notebook_path = f"{notebooks_dir}/eda_notebook.ipynb"
        self._generate_eda_notebook(eda_results, eda_notebook_path)
        generated_files['eda_notebook'] = eda_notebook_path
        
        # 4. Features Notebook
        features_notebook_path = f"{notebooks_dir}/features_notebook.ipynb"
        self._generate_features_notebook(features, features_notebook_path)
        generated_files['features_notebook'] = features_notebook_path
        
        return generated_files
    
    def _generate_executive_summary(self, strategy, eda, features, models) -> str:
        """Generates executive summary (Gemini-powered if available)."""
        
        if self.gemini_enabled:
            try:
                prompt = f"""
Generate an executive summary for a Kaggle competition analysis.

Competition: {strategy['competition_name']}
Problem Type: {strategy['problem_type']}
Best Model: {models['best_model']} ({models['best_cv_score']:.4f} accuracy)
Features Created: {features['total_features']}

Include:
- Competition overview
- Key data insights
- Feature engineering highlights
- Model performance summary
- Recommended next steps

Keep it professional and concise (500 words max).
"""
                response = self.client.models.generate_content(
                    model=self.model,
                    contents=prompt
                )
                return f"# Executive Summary\n\n*Generated by Gemini AI*\n\n{response.text}"
            except:
                pass
        
        # Fallback summary
        return f"""# Executive Summary

## Competition: {strategy['competition_name']}

### Problem Overview
- **Type**: {strategy['problem_type']}
- **Metric**: {strategy['metric']}
- **Dataset**: {eda['shape'][0]} rows × {eda['shape'][1]} columns

### Data Insights
- **Missing Data**: {sum(1 for v in eda['missing_percent'].values() if v > 0)} columns with missing values
- **Features**: {len(eda['columns'])} original features

### Feature Engineering
- **Created Features**: {features['total_features']}
- **Top Features**: {', '.join(list(features['feature_importance'].keys())[:5])}

### Model Performance
- **Best Model**: {models['best_model']}
- **Cross-Validation Accuracy**: {models['best_cv_score']:.4f}
- **Models Tested**: {len(models['comparison'])}

### Recommended Next Steps
1. **Hyperparameter Tuning**: Optimize the best model's parameters
2. **Feature Interactions**: Create more sophisticated interaction features
3. **Ensemble Methods**: Combine multiple models for better performance
4. **Domain Research**: Investigate domain-specific patterns
5. **External Data**: Consider augmenting with external datasets

### Conclusion
The agent system has successfully generated a competitive baseline solution. The {models['best_model']} model achieved {models['best_cv_score']:.2%} accuracy, positioning this submission in a competitive range. Human data scientists can now focus on advanced optimization strategies.

---
*Generated by Kaggle Competition Co-Pilot Agent System*
"""
    
    def _generate_model_report(self, models: Dict) -> str:
        """Generates model comparison report."""
        report = f"""# Model Comparison Report

## Overview
Trained and evaluated {len(models['comparison'])} baseline models using 5-fold cross-validation.

## Results

| Model | Mean Accuracy | Std Dev |
|-------|--------------|---------|
"""
        for result in models['comparison']:
            report += f"| {result['model']} | {result['cv_mean']:.4f} | {result['cv_std']:.4f} |\n"
        
        report += f"""
## Best Model: {models['best_model']}
- **Cross-Validation Accuracy**: {models['best_cv_score']:.4f}
- **Standard Deviation**: {models['all_results'][models['best_model']]['cv_std_accuracy']:.4f}

## Feature Importance (Top 10)
"""
        best_model_data = models['all_results'][models['best_model']]
        if best_model_data.get('feature_importance'):
            for feature, importance in list(best_model_data['feature_importance'].items())[:10]:
                report += f"- **{feature}**: {importance:.4f}\n"
        
        return report
    
    def _generate_eda_notebook(self, eda_results: Dict, output_path: str):
        """Generates EDA Jupyter notebook."""
        nb = nbf.v4.new_notebook()
        
        cells = [
            nbf.v4.new_markdown_cell("# Exploratory Data Analysis\n\n*Auto-generated by Data Explorer Agent*"),
            nbf.v4.new_markdown_cell(f"## Dataset Overview\n\n{eda_results['summary']}"),
            nbf.v4.new_markdown_cell("## Visualizations\n\nThe following visualizations were generated:"),
        ]
        
        for viz_path in eda_results.get('visualizations', []):
            cells.append(nbf.v4.new_markdown_cell(f"![Visualization]({viz_path})"))
        
        nb['cells'] = cells
        
        with open(output_path, 'w') as f:
            nbf.write(nb, f)
    
    def _generate_features_notebook(self, features: Dict, output_path: str):
        """Generates feature engineering notebook."""
        nb = nbf.v4.new_notebook()
        
        cells = [
            nbf.v4.new_markdown_cell("# Feature Engineering\n\n*Auto-generated by Feature Engineer Agent*"),
            nbf.v4.new_markdown_cell(f"## Features Created\n\nTotal: {features['total_features']} features"),
            nbf.v4.new_markdown_cell("### Feature List\n\n" + '\n'.join([f"- {f}" for f in features.get('created_features', [])])),
            nbf.v4.new_markdown_cell("## Feature Importance\n\nTop 10 features by importance:"),
        ]
        
        importance_md = "\n".join([f"{i+1}. **{feat}**: {imp:.4f}" 
                                   for i, (feat, imp) in enumerate(list(features['feature_importance'].items())[:10])])
        cells.append(nbf.v4.new_markdown_cell(importance_md))
        
        nb['cells'] = cells
        
        with open(output_path, 'w') as f:
            nbf.write(nb, f)
